name: Coba ssh

on:
  push: 
    branches:
      - master

jobs:
  build:
    access_server:
      name: Access server
      runs-on: ubuntu-latest
      steps:
        - name: Create a file
          uses: appleboy/ssh-action@master
          with:
            host: 10.10.0.72
            username: appsadmin
            password: 135790AaA
            script: echo hello world > hello.txt
